### ISSUE TITLE
ModuleNotFoundError: No module named 'models.gradient_scaler'

### ISSUE THREAD

**Issue by ghost** [intel-isl/MultiObjectiveOptimization#11]
After executing the python multi_task/train_multi_task.py --param_file=./sample.json, 
i got error below:
   from models.gradient_scaler import MinNormElement
ModuleNotFoundError: No module named 'models.gradient_scaler'

**Comment by mustafaparekh53** [comment]
I also got the same error. Do share if you found a solution.

**Comment by SophiaHan6** [comment]
It seems 'MinNormElement' function is not used in the code so I just commented out

**Comment by ozansener** [comment]
It is an import which stayed there after a file re-organization. You can safely comment it out. I also removed it from the file in the master branch
