### ISSUE TITLE
Comment mentioned a missing notebook

### ISSUE THREAD

**Issue by milos-popovic** [intel-isl/MultiObjectiveOptimization#13]
https://github.com/intel-isl/MultiObjectiveOptimization/blob/1c6d0d503ccf33cc83d5b6c356ca2fc2bf255606/multi_task/train_multi_task.py#L158

This comment mentions a notebook which cannot be found in the repository. Is it available somewhere else?

**Comment by ozansener** [comment]
Please send me an e-mail. I can either share it with you. The notebook is not in the repo, since it needs to be cleaned
