### ISSUE TITLE
How to get the mean of error in the CelebA experiment

### ISSUE THREAD

**Issue by tianheyu927** [intel-isl/MultiObjectiveOptimization#15]
Seems like the code only provide classification accuracy and negative log-likelihood loss instead of the mean of error shown in Table 1 in the paper. Is there any way that we can get that number? Thanks!

**Comment by ozansener** [comment]
We treat them as separate binary classification problems (separate tasks) so mean error means average of 1-class classification errors. Hence, it is average of 1 - classification accuracy.
