### ISSUE TITLE
Get test accuracy for MultiMNIST

### ISSUE THREAD

**Issue by tianheyu927** [intel-isl/MultiObjectiveOptimization#16]
Hi,

I'm wondering how I can get the test accuracy for MultiMNIST. Right now, it seems to me that the metric results logged at each epoch are the test accuracies. Can you clarify how you obtain the test accuracy numbers in the paper? Thanks!

**Comment by ozansener** [comment]
Currently it reports validation accuracy. What we do is choose the model(epoch) with the highest validation accuracy. Moreover, we use it to compute the test accuracy separately. 

This is also not related to the code so please send me an e-mail (ozansener@gmail.com) if you have more questions. Closing it!
