### ISSUE TITLE
instance segmentation

### ISSUE THREAD

**Issue by CF2220160244** [intel-isl/MultiObjectiveOptimization#17]
During the inference, i  predict instance vectors for x/y coordinates,
How can i get the final instance output?

**Comment by ozansener** [comment]
You need to run some sort of clustering algorithm to get instance labels. Our metrics and loss only use x/y coordinates. You can check http://openaccess.thecvf.com/content_cvpr_2018/papers/Kendall_Multi-Task_Learning_Using_CVPR_2018_paper.pdf for details as they use OPTICS algorithm. Their implementation is here: https://github.com/alexgkendall/OPTICS_Clustering
