### ISSUE TITLE
different sizes of gradient

### ISSUE THREAD

**Issue by wtomin** [intel-isl/MultiObjectiveOptimization#18]
Hi, thanks for sharing your code!

I have one question about the size of gradient. I found that in the current code, only 2D gradient is supported. But if the parameter has 4 dimensional, such as (batch-size, N, width, height), how should I modify the min-norm solver ?

**Comment by ozansener** [comment]
Vectorizing them should be fine. Basically, the code only uses dot product of gradients. Hence, as long as dot products are correctly computed, you should be fine.
