### ISSUE TITLE
Unstable GPU usage while Training on Cityscapes

### ISSUE THREAD

**Issue by SophiaHan6** [intel-isl/MultiObjectiveOptimization#21]
Hi,

Thanks for open-sourcing the awesome code.

I am using PyTorch 3.6 to run the equal-weights setup(without using mgda) on Cityscapes with a single GPU, but the GPU usage is extremely unstable and keeps shifting between 0 - 99. Do you know what could cause that?

Thanks

**Comment by ozansener** [comment]
We did not do any memory benchmarking. But, if you do not want to use mgda, you can probably make it much more efficient. We compute internal representations (z) in the code. You do not need it if you are doing equal weights. However, this codebase is only for MGDA.
