### ISSUE TITLE
KeyError with the tensorboardX

### ISSUE THREAD

**Issue by haolun-wu** [intel-isl/MultiObjectiveOptimization#22]
Hello, can anybody tell me how to fix this issue? Is this a version inconsistency with the tensorboardX?
Cuz I am exactly run the code offered on the github without changing anything.
Appreciate in advance.

[
<img width="1439" alt="截屏2020-04-19 16 06 50" src="https://user-images.githubusercontent.com/33157137/79698637-366bf880-8258-11ea-89c6-ab3217f89355.png">
](url)

**Comment by ozansener** [comment]
Our code uses all hyper params in the filename. In some OS, such long filenames are not possible. So, just replace L41 of train_multi_task.py (https://github.com/intel-isl/MultiObjectiveOptimization/blob/master/multi_task/train_multi_task.py#L41) to not include scale hyper-param in filename as 
```python
        if 'tasks' in key or 'scales' in key:
            continue
```

**Comment by haolun-wu** [comment]
Thanks Ozan, it works!

Your work is fantastic, I will learn from it.

Best,
Haolun





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ozan Sener"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 上午6:44
收件人:&nbsp;"intel-isl/MultiObjectiveOptimization"<MultiObjectiveOptimization@noreply.github.com&gt;;
抄送:&nbsp;"Raven_WU"<573214193@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [intel-isl/MultiObjectiveOptimization] KeyError with the tensorboardX (#22)





 
Our code uses all hyper params in the filename. In some OS, such long filenames are not possible. So, just replace L41 of train_multi_task.py (https://github.com/intel-isl/MultiObjectiveOptimization/blob/master/multi_task/train_multi_task.py#L41) to not include scale hyper-param in filename as
         if 'tasks' in key or 'scales' in key:             continue
