### ISSUE TITLE
the time of "loss_data[t] = loss.data[0]" is so long

### ISSUE THREAD

**Issue by peterytian** [intel-isl/MultiObjectiveOptimization#23]
I find that "loss_data[t] = loss.data[0]" will cost 0.5s.
Is there any way to decrease the cost?

**Comment by peterytian** [comment]
Is there a gpu version of the solver?

**Comment by youandeme** [comment]
Hi,have you reproduced the results on MultiMNIST?  Would you like to tell me the params you chosen?Thanks.
