### ISSUE TITLE
 size of the segmentation output

### ISSUE THREAD

**Issue by iris0329** [intel-isl/MultiObjectiveOptimization#28]
I find the input size of CityScapes is 256x512, but in the transform, the target is resize into 32x64. what's more, the measure metrix is based on 32x64. 

So, why the target size is not 256x512, just same as the input size?

**Comment by ozansener** [comment]
The cityscapes model is taken directly from https://github.com/CSAILVision/semantic-segmentation-pytorch/blob/master/models/models.py
