### ISSUE TITLE
run error, Please help me, Thanks

### ISSUE THREAD

**Issue by zshy1205** [intel-isl/MultiObjectiveOptimization#29]
I use "
"algorithm": "mgda",
"use_approximation": true,", That's mean the MGDA_UB is used。
When I trained the task，At the begin time, It can run true. But when it run some steps, It will get error: "RuntimeError: CUDA out of memory." ，I use torch_version==v1.1.0， Is it torch_version question?

**Comment by ozansener** [comment]
We are copying gradients for computation, you might be running out of memory.
