### ISSUE TITLE
Is MultiMNIST data avaliable publicly

### ISSUE THREAD

**Issue by YoungGer** [intel-isl/MultiObjectiveOptimization#3]
Thanks for you code.
I want to know where can I find the MultiMNIST dataset used in your paper if it's avaliable now.

**Comment by ozansener** [comment]
Here is the link: https://drive.google.com/file/d/1FLVO0l8vMXz-UaInCRPZZKx-rv_MPSLA/view?usp=sharing Loader in the code should be able to read it if you put in the right folder and set the folder in configs.json

I also added the link to my page

**Comment by YoungGer** [comment]
OK, thanks for your help.

**Comment by akamboj2** [comment]
It seems like this link is now broken?

Why is this multimnist dataset so hard to find online?
