### ISSUE TITLE
How to convert .pkl file to .onnx model. I mean there are two parts of the whole model.

### ISSUE THREAD

**Issue by sh2120170809** [intel-isl/MultiObjectiveOptimization#33]
For example: 
model_task0  = ResNet() + FaceAttributeNet()
model_task1  = ResNet() + FaceAttributeNet()
How can i convert the .pkl data to onnx model

**Comment by besmaguesmi** [comment]
Hello, I have the same question! any help?

**Comment by nikkorejz** [comment]
Any updates?

**Comment by besmaguesmi** [comment]
@ArtiX-GP Try to save your model to another format (e.g PyTorch) and then convert it to onnx

**Comment by DevLob-zz** [comment]
import joblib
from onnxmltools import convert_sklearn
import tensorflow as tf


print(tf.__version__)

# Load the scikit-learn model from the .pkl file
loaded_model = joblib.load('model.pkl')

# Convert the scikit-learn model to ONNX format
onnx_model = convert_sklearn(loaded_model, 'ONNXmodel')

with open('C:/Users/asalim/Downloads/TableHeaders/TableHeaders/Model.onnx', 'wb') as f:
    f.write(onnx_model.SerializeToString())
