### ISSUE TITLE
sample.json for Multi Mnist?

### ISSUE THREAD

**Issue by masoudpz** [intel-isl/MultiObjectiveOptimization#9]
Hi. thanks for sharing.
what is the structure for sample.json and config.json when I want to use code for multiMnist dataset?

**Comment by JunwenBai** [comment]
How did you design the jsons for mnist?

**Comment by ozansener** [comment]
This is the hyperparameter set we used: 

`optimizer=SGD|batch_size=256|lr=0.05|normalization_type=none`

Json structure is:
```
{
    "optimizer": "SGD",
    "batch_size": 256,
    "lr": 0.05,
    "dataset": "mnist",
    "tasks": ["L", "R"],
    "normalization_type": "none",
    "algorithm": "mgda",
    "use_approximation": true,
    "scales": {"L":0.5, "R":0.5}
}
```
